cpufeq: schedutil: Remove CAF's fuckery
CAF's hispeed boost and predicted load features aren't any good. Remove
them entirely to prevent userspace from trying to enable them
(specifically pl) and to reduce useless overhead in schedutil, since it
runs *very* often.

Signed-off-by: Danny Lin <danny@kdrag0n.dev>

jprimero15 fix:
../kernel/sched/cpufreq_schedutil.c:295:3: error: implicit
declaration of function 'sugov_walt_adjust' [-Werror,-Wimplicit-function-declaration]
                sugov_walt_adjust(j_sg_cpu, &util, &max);
                ^

Signed-off-by: Joshua Primero <jprimero155@gmail.com>